version: '2'

services:
  mqtt_gw:
    image: eclipse-mosquitto:1.4.10
    restart: always
    ports:
      - 1801:1883   
  db_gw:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=bkcloud
      - MYSQL_DATABASE=iot
      - MYSQL_USER=bkcloud
      - MYSQL_PASSWORD=bkcloud
    ports:
      - 3301:3306   
  influxdb_gw:
    image: influxdb:1.3.6
    restart: always 
    ports:
      - 8085:8086
  node_red_gw:
    image: nodered/node-red-docker
    restart: always
    volumes:
      - ./node-red-gw/data:/data
    ports:
      - 1881:1880
    stdin_open: true
    tty: true
    external_links:
      - mqtt_gw:mqtt_gw
      - db_gw:db_gw
      - influxdb_gw:influxdb_gw
    command: [sh, -c, "cd /data && npm i mysql@2.15.0 influx@5.0.7 express@4.16.0 mustache@2.3.0 moment@2.19.2 && cd /usr/src/node-red && npm start -- --userDir /data"]

  mqtt_server:
    image: eclipse-mosquitto:1.4.10
    restart: always
    ports:
      - 1800:1883   
  influxdb_server:
    image: influxdb:1.3.6
    restart: always 
    ports:
      - 8086:8086

  db_server:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=bkcloud
      - MYSQL_DATABASE=iot
      - MYSQL_USER=bkcloud
      - MYSQL_PASSWORD=bkcloud

    ports:
      - 3300:3306    

  node_red_server:
    image: nodered/node-red-docker
    # build: node-red
    restart: always
    volumes:
      - ./node-red-server/data:/data
    ports:
      - 1880:1880
    stdin_open: true
    tty: true
    external_links:
      - mqtt_server:mqtt_server
      - db_server:db_server
      - influxdb_server:influxdb_server
    # command: [sh, -c, "cd /data && npm i node-red-contrib-meo-esp node-red-dashboard && node-red --settings /data/settings.js"]
    command: [sh, -c, "cd /data && npm i mysql@2.15.0 influx@5.0.7 express@4.16.0 mustache@2.3.0 moment@2.19.2 && cd /usr/src/node-red && npm start -- --userDir /data"]
    # command: ["npm", "start", "--", "--userDir", "/data"]
